namespace Victory.DataLayer.Serialization.Event
{
	public enum enumRewardType
	{
		None = 0, 
		Busted = 1, 
		Evaded = 2, 
		RepAmplifier = 3, 
		TokenAmplifier = 4, 
		SkillMostWanted = 5, 
		SkillSocialite = 6, 
		SkillTycoon = 7, 
		SkillTerminator = 8, 
		HeatLevel = 9, 
		PursuitLength = 10, 
		Bounty = 11, 
		CopCarsDeployed = 12, 
		CopCarsRammed = 13, 
		CopCarsDisabled = 14, 
		RhinosDisabled = 15, 
		CostToState = 16, 
		RoadblocksDodged = 17, 
		SpikeStripsDodged = 18, 
		Infractions = 19, 
		LevelCap = 20, 
		EntitlementLevelCap = 21, 
		TopenCap = 22, 
		SafehouseReached = 23, 
		Finished = 24, 
		TimeBonus = 25, 
		Player1 = 26, 
		Player2 = 27, 
		Player3 = 28, 
		Player4 = 29, 
		StrikeFree = 30, 
		TeamStrikeBonus = 31, 
		PowerupBonus = 32, 
		SkillMod = 33, 
	}
}
